version: '3.3'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
  
  userservice:
    build:
      context: ./userservice  # Adjust the build context to include the parent directory
      dockerfile: Dockerfile  # Specify the path to the Dockerfile relative to the build context
    ports:
      - "3001:3001"
    environment:
      - MONGO_URL=
    depends_on:
      - mongo
